workflows:
  version: 2
  0am:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
             branches:
               only:
                 - master
    jobs:
      - download-counter
  3am:
    triggers:
      - schedule:
          cron: "0 3 * * *"
          filters:
             branches:
               only:
                 - master
    jobs:
      - download-counter
  6am:
    triggers:
      - schedule:
          cron: "0 6 * * *"
          filters:
             branches:
               only:
                 - master
    jobs:
      - download-counter
  9am:
    triggers:
      - schedule:
          cron: "0 9 * * *"
          filters:
             branches:
               only:
                 - master
    jobs:
      - download-counter
  0pm:
    triggers:
      - schedule:
          cron: "0 12 * * *"
          filters:
             branches:
               only:
                 - master
    jobs:
      - download-counter
  3pm:
    triggers:
      - schedule:
          cron: "0 15 * * *"
          filters:
             branches:
               only:
                 - master
    jobs:
      - download-counter
  6pm:
    triggers:
      - schedule:
          cron: "0 18 * * *"
          filters:
             branches:
               only:
                 - master
    jobs:
      - download-counter
  9pm:
    triggers:
      - schedule:
          cron: "0 21 * * *"
          filters:
             branches:
               only:
                 - master
    jobs:
      - download-counter
jobs:
  download-counter:
  build:
    executor:
      machine: true
    steps:
      - checkout
      - run:
          name: Instalação de dependências
          command: sudo apt update;sudo apt install -y git python-requests wget
      - run:
          name: Atualização do contador de downloads
          command: |
            wget -q https://raw.githubusercontent.com/mmilidoni/github-downloads-count/master/gdc;chmod +x -v gdc
            ./gdc rauldipeas Unity-XP | tac | awk 'NR <=1' | awk '{print $1}'  | echo +$(xargs) Downloads > website/download-counter/download-counter.log;rm -rfv gdc
            git config --global user.email "rauldipeas@mail.com";git config --global user.name "Raul Dipeas"
            git add .; git commit -m "^download-counter"
            git push http://rauldipeas:$GITHUB_ACCESS_TOKEN@github.com/rauldipeas/Unity-XP.git HEAD:master