pool:
  vmImage: 'ubuntu-18.04'
variables:
  - group: GitHub
trigger: none
schedules:
  - cron: "0 0 * * *"
    displayName: Meia-noite
    branches:
      include:
      - master
  - cron: "0 6 * * *"
    displayName: 6 da manhã
    branches:
      include:
      - master
  - cron: "0 12 * * *"
    displayName: Meio-dia
    branches:
      include:
      - master
  - cron: "0 18 * * *"
    displayName: 6 da tarde
    branches:
      include:
      - master
steps:
  - script: sudo apt update;sudo apt install -y git python-requests wget
    displayName: Instalação de dependências
  - script: bash website/download-counter/download-counter.sh
    displayName: Atualização do contador de downloads
