name: Unity XP (download-counter)
on:
  schedule:
    - cron: "0 0 * * *"
    - cron: "0 3 * * *"
    - cron: "0 6 * * *"
    - cron: "0 9 * * *"
    - cron: "0 12 * * *"
    - cron: "0 15 * * *"
    - cron: "0 18 * * *"
    - cron: "0 21 * * *"
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Instalação de dependências
      run: sudo apt update;sudo apt install -y git python-requests wget
    - name: Atualização do contador de downloads
      run: |
        wget -q https://raw.githubusercontent.com/mmilidoni/github-downloads-count/master/gdc;chmod +x -v gdc
        ./gdc rauldipeas Unity-XP | tac | awk 'NR <=1' | awk '{print $1}'  | echo +$(xargs) Downloads > website/download-counter/download-counter.log;rm -rfv gdc
        git config --global user.email "rauldipeas@mail.com";git config --global user.name "Raul Dipeas"
        git add .; git commit -m "^download-counter"
        git push http://rauldipeas:${{ secrets.GITHUB_ACCESS_TOKEN }}@github.com/rauldipeas/Unity-XP.git HEAD:master