name: Unity XP (download-counter)
on:
  schedule:
    - cron: "*/60 * * * *"
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Instalação de dependências
      run: sudo apt update;sudo apt install -y git python-requests wget
    - name: Atualização do contador de downloads
      run: |
        wget -q https://raw.githubusercontent.com/mmilidoni/github-downloads-count/master/gdc;chmod +x gdc
        ./gdc rauldipeas unity-xp | tac | awk 'NR <=1' | awk '{print $1}'  | echo +$(xargs) Downloads > website/download-coubter/download-counter.log
        #git clone https://github.com/rauldipeas/Unity-XP;cd Unity-XP;mkdir -pv website/download-counter
        #cp ../download-counter.log website/download-counter/download-counter.log
        git config --global user.email "rauldipeas@mail.com";git config --global user.name "Raul Dipeas"
        git add .; git commit -m "^download-counter"
        git push http://rauldipeas:${{ secrets.GITHUB_ACCESS_TOKEN }}@github.com/rauldipeas/Unity-XP.git HEAD:master