name: Unity XP (download-counter)
on:
  schedule:
    - cron: "*/30 * * * *"
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Netlify deploy download-counter
      run: curl -X POST -d {} https://api.netlify.com/build_hooks/5de16402ae043f52c6e457dd