name: Unity XP (ISO)
on:
  push:
    branches-ignore:
      - 'releases/**'
    paths-ignore:
      - '.gitbook.yml'
      - '_config.yml'
      - 'readme.md'
      - 'update.sh'
      - '.github/workflows/download-counter.yml'
      - 'docs/**'
      - 'resources/**'
      - 'screenshots/**'
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Instalação de dependências
      run: |
            sudo apt update
            sudo apt install -y apt-transport-https debootstrap mtools npm rsync squashfs-tools sshpass xorriso
    - name: Instalação do MEGAcmd
      run: |
            sudo apt install -y autoconf libtool g++ libcrypto++-dev libz-dev libsqlite3-dev libssl-dev libcurl4-gnutls-dev libreadline-dev libpcre++-dev libsodium-dev libc-ares-dev libfreeimage-dev libavcodec-dev libavutil-dev libavformat-dev libswscale-dev libmediainfo-dev libzen-dev libuv1-dev
            git clone https://github.com/meganz/MEGAcmd.git
            cd MEGAcmd && git submodule update --init --recursive
            sh autogen.sh;./configure;make;sudo make install
    - name: Compilação da imagem de instalação
      run: bash code/build.sh
    - name: Upload da imagem de instalação para o Dropbox
      run: |
            mega-login 'rauldipeas@mail.com' '${{ secrets.MEGA_PASS }}'
            mega-put $HOME/Unity-XP/iso/unity-xp-19.10-amd64.* /Unity-XP/
    #- name: Upload da imagem de instalação para o SourceForge
    #  run: sshpass -p '${{ secrets.SOURCEFORGE_PASS }}' rsync -avP -e 'ssh -o StrictHostKeyChecking=no' $HOME/Unity-XP/iso/unity-xp-19.10-amd64.* rauldipeas@frs.sourceforge.net:/home/frs/project/unity-xp/ISO