name: Unity XP (ISO)
on:
  push:
    branches-ignore:
      - 'releases/**'
    paths-ignore:
      - '.gitbook.yml'
      - '_config.yml'
      - 'readme.md'
      - 'update.sh'
      - '.github/workflows/download-counter.yml'
      - 'docs/**'
      - 'resources/**'
      - 'screenshots/**'
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Instalação de dependências
      run: sudo apt update;sudo apt install -y apt-transport-https debootstrap mktorrent mtools rsync squashfs-tools sshpass xorriso
    - name: Compilação da imagem de instalação
      run: bash code/build.sh
    - name: Criação do arquivo torrent da imagem de instalação
      run: cd $HOME/Unity-XP/iso;mktorrent -v -a udp://tracker.openbittorrent.com:80 -c "Unity eXPerience https://unityxp.tk" -n "unity-xp-19.10-amd64" -w https://iweb.dl.sourceforge.net/project/unity-xp/ISO/unity-xp-19.10-amd64.iso unity-xp-19.10-amd64.iso
    - name: Upload da imagem de instalação para o Yandex disk
      run: |
            wget -c http://repo.yandex.ru/yandex-disk/yandex-disk_latest_amd64.deb
            sudo apt install -y ./yandex-disk*.deb
            yandex-disk token -p '${{ secrets.YANDEX_PASS }}' rauldipeas
            echo 'dir=$HOME/Unity-XP/iso' | tee -a $HOME/.config/yandex-disk/config.cfg
            yandex-disk sync
#    - name: Upload da imagem de instalação para o Nextcloud
#      run: 'curl -k -T $HOME/Unity-XP/iso/unity-xp-19.10-amd64.iso -u "${{ secrets.NEXTCLOUD_ID }}" -H "X-Requested-With: XMLHttpRequest" https://cs.unixuniverse.com.br/cloud/public.php/webdav/unity-xp-19.10-amd64.iso'
    - name: Upload da imagem de instalação para o SourceForge
      run: sshpass -p '${{ secrets.SOURCEFORGE_PASS }}' rsync -avP -e 'ssh -o StrictHostKeyChecking=no' $HOME/Unity-XP/iso/unity-xp-19.10-amd64.* rauldipeas@frs.sourceforge.net:/home/frs/project/unity-xp/ISO
    - name: Notificação no Telegram
      uses: appleboy/telegram-action@master
      with:
        to: -1001205590386
        token: ${{ secrets.TELEGRAM_TOKEN }}
        args: Uma nova imagem de instalação do Unity XP está disponível para download no site https://unityxp.tk
        photo: resources/images/github-hero.png
