name: Unity XP (ISO)
on:
  push:
    branches-ignore:
      - 'releases/**'
    paths-ignore:
      - '.gitbook.yml'
      - '_config.yml'
      - 'readme.md'
      - 'update.sh'
      - '.github/workflows/download-counter.yml'
      - 'docs/**'
      - 'resources/**'
      - 'screenshots/**'
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Instalação de dependências
      run: sudo apt update;sudo apt install -y apt-transport-https debootstrap mtools npm rsync squashfs-tools sshpass xorriso
    - name: Compilação da imagem de instalação
      run: bash code/build.sh
    - name: Upload da imagem de instalação para o Dropbox
      run: 'cd $HOME/Unity-XP/iso/;curl -X POST https://content.dropboxapi.com/2/files/upload --header "Authorization: Bearer ${{ secrets.DROPBOX_API_KEY }}" --header "Dropbox-API-Arg: {\"path\": \"/unity-xp-19.10-amd64.iso\"}" --header "Content-Type: application/octet-stream" --data-binary @unity-xp-19.10-amd64.iso --verbose'
    #- name: Upload da imagem de instalação para o SourceForge
    #  run: sshpass -p '${{ secrets.SOURCEFORGE_PASS }}' rsync -avP -e 'ssh -o StrictHostKeyChecking=no' $HOME/Unity-XP/iso/unity-xp-19.10-amd64.* rauldipeas@frs.sourceforge.net:/home/frs/project/unity-xp/ISO